### ISSUE TITLE
Exercise 5.C.1

### ISSUE THREAD

**Issue by ghost** [guestname/linear-algebra-done-right-solutions#1]
I think you're improperly invoking Theorem 5.41. Just because V is diagonalizable doesn't mean that its finite, which the theorem assumes. However, I think (hope, for my sake) that you can tweak it to work with infinitely-many distinct eigenvalues and thus infinitely-many eigenspaces.

Also, there is a minor typo in the third chunk of text, one of the \frac{1}{\lambda_1} 's needs to be a \frac{1}{\lambda_j}

**Comment by celiopassos** [comment]
Well, Axler only defines bases (and hence matrices and diagonalizable operators) for finite-dimensional vector spaces, so I think he wants us to assume that V is finite-dimensional in that exercise.

**Comment by ghost** [comment]
After a closer reading, I agree.
