### ISSUE TITLE
Mistake in 7.A exercise 2 solution

### ISSUE THREAD

**Issue by huzeou** [guestname/linear-algebra-done-right-solutions#3]
You can not conclude the last equality, because inner product with v being the same doesn't imply the two vectors are the same.
What's more, your solution implies that eigen-vectors are the same for T and adjoint of T, but this is not guaranteed for general T, it is only true when T is normal.

**Comment by celiopassos** [comment]
Thanks, fixed it.

I don't know what got in to me in order to write that blasphemy.
