### ISSUE TITLE
Solution of 6.B.11 uses a theorem for finite dimensional vector spaces, even though the vector space might be infinite dimensional

### ISSUE THREAD

**Issue by philip-bl** [guestname/linear-algebra-done-right-solutions#5]
In 6.B.11 you say:

By Theorem 1 in
Chapter 3 notes we have
$$
\operatorname{span}(\varphi) = (\operatorname{null} \varphi)^0 = (\operatorname{null} \psi)^0 = \operatorname{span}(\psi).
$$

The theorem 1 in chapter 3 is for finite-dimensional vector spaces. Therefore, it's inapplicable here.

**Comment by celiopassos** [comment]
Late, but fixed. Thanks.
